name: Harvest S&P 500

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # Install any CRAN packages you need (here only rvest)
          install-packages: |
            rvest
            xml2  

      - name: Run harvest script
        run: |
          Rscript ./R/harvest_sp500.r

      - name: Commit and push updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily update: S&P 500 list"
          file_pattern: data/sp500.csv
